/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAnimaisRouteImport } from './routes/_authenticated/animais'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedOdontogramaRouteImport } from './routes/_authenticated/odontograma'
import { Route as AuthenticatedProntuariosRouteImport } from './routes/_authenticated/prontuarios'
import { Route as AuthenticatedRuralRouteImport } from './routes/_authenticated/rural'
import { Route as AuthenticatedVacinasRouteImport } from './routes/_authenticated/vacinas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnimaisRoute = AuthenticatedAnimaisRouteImport.update({
  id: '/animais',
  path: '/animais',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOdontogramaRoute =
  AuthenticatedOdontogramaRouteImport.update({
    id: '/odontograma',
    path: '/odontograma',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProntuariosRoute =
  AuthenticatedProntuariosRouteImport.update({
    id: '/prontuarios',
    path: '/prontuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRuralRoute = AuthenticatedRuralRouteImport.update({
  id: '/rural',
  path: '/rural',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVacinasRoute = AuthenticatedVacinasRouteImport.update({
  id: '/vacinas',
  path: '/vacinas',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/animais': typeof AuthenticatedAnimaisRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/odontograma': typeof AuthenticatedOdontogramaRoute
  '/prontuarios': typeof AuthenticatedProntuariosRoute
  '/rural': typeof AuthenticatedRuralRoute
  '/vacinas': typeof AuthenticatedVacinasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/animais': typeof AuthenticatedAnimaisRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/odontograma': typeof AuthenticatedOdontogramaRoute
  '/prontuarios': typeof AuthenticatedProntuariosRoute
  '/rural': typeof AuthenticatedRuralRoute
  '/vacinas': typeof AuthenticatedVacinasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/animais': typeof AuthenticatedAnimaisRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/odontograma': typeof AuthenticatedOdontogramaRoute
  '/_authenticated/prontuarios': typeof AuthenticatedProntuariosRoute
  '/_authenticated/rural': typeof AuthenticatedRuralRoute
  '/_authenticated/vacinas': typeof AuthenticatedVacinasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/politica-de-privacidade'
    | '/termos'
    | '/agenda'
    | '/animais'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/odontograma'
    | '/prontuarios'
    | '/rural'
    | '/vacinas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/politica-de-privacidade'
    | '/termos'
    | '/agenda'
    | '/animais'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/odontograma'
    | '/prontuarios'
    | '/rural'
    | '/vacinas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/politica-de-privacidade'
    | '/termos'
    | '/_authenticated/agenda'
    | '/_authenticated/animais'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/odontograma'
    | '/_authenticated/prontuarios'
    | '/_authenticated/rural'
    | '/_authenticated/vacinas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/animais': {
      id: '/_authenticated/animais'
      path: '/animais'
      fullPath: '/animais'
      preLoaderRoute: typeof AuthenticatedAnimaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/odontograma': {
      id: '/_authenticated/odontograma'
      path: '/odontograma'
      fullPath: '/odontograma'
      preLoaderRoute: typeof AuthenticatedOdontogramaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prontuarios': {
      id: '/_authenticated/prontuarios'
      path: '/prontuarios'
      fullPath: '/prontuarios'
      preLoaderRoute: typeof AuthenticatedProntuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rural': {
      id: '/_authenticated/rural'
      path: '/rural'
      fullPath: '/rural'
      preLoaderRoute: typeof AuthenticatedRuralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vacinas': {
      id: '/_authenticated/vacinas'
      path: '/vacinas'
      fullPath: '/vacinas'
      preLoaderRoute: typeof AuthenticatedVacinasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAnimaisRoute: typeof AuthenticatedAnimaisRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedOdontogramaRoute: typeof AuthenticatedOdontogramaRoute
  AuthenticatedProntuariosRoute: typeof AuthenticatedProntuariosRoute
  AuthenticatedRuralRoute: typeof AuthenticatedRuralRoute
  AuthenticatedVacinasRoute: typeof AuthenticatedVacinasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAnimaisRoute: AuthenticatedAnimaisRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedOdontogramaRoute: AuthenticatedOdontogramaRoute,
  AuthenticatedProntuariosRoute: AuthenticatedProntuariosRoute,
  AuthenticatedRuralRoute: AuthenticatedRuralRoute,
  AuthenticatedVacinasRoute: AuthenticatedVacinasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
